# Generated by Django 3.0.5 on 2020-04-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=200)),
                ('late_drop_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_head', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('office_address', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=200)),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ntnyPth.Zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='TA_teaching_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_team_id', models.IntegerField()),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Student')),
            ],
            options={
                'unique_together': {('student_email', 'teaching_team_id')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveIntegerField()),
                ('limit', models.IntegerField()),
                ('teaching_team_id', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Course')),
            ],
            options={
                'unique_together': {('course_id', 'sec_no')},
            },
        ),
        migrations.CreateModel(
            name='Prof_teaching_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_team_id', models.IntegerField()),
                ('prof_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Professor')),
            ],
            options={
                'unique_together': {('prof_email', 'teaching_team_id')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_no', models.PositiveIntegerField()),
                ('student_email', models.CharField(max_length=20)),
                ('post_info', models.CharField(max_length=1000)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Course')),
            ],
            options={
                'unique_together': {('course_id', 'post_no')},
            },
        ),
        migrations.CreateModel(
            name='Homework_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveIntegerField()),
                ('hw_no', models.PositiveIntegerField()),
                ('grade', models.FloatField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Course')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Student')),
            ],
            options={
                'unique_together': {('student_email', 'course_id', 'sec_no', 'hw_no')},
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveIntegerField()),
                ('hw_no', models.PositiveIntegerField()),
                ('hw_details', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Course')),
            ],
            options={
                'unique_together': {('course_id', 'sec_no', 'hw_no')},
            },
        ),
        migrations.CreateModel(
            name='Exam_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveIntegerField()),
                ('exam_no', models.PositiveIntegerField()),
                ('grades', models.FloatField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Course')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Student')),
            ],
            options={
                'unique_together': {('student_email', 'course_id', 'sec_no', 'exam_no')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveIntegerField()),
                ('exam_no', models.PositiveIntegerField()),
                ('exam_details', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Course')),
            ],
            options={
                'unique_together': {('course_id', 'sec_no', 'exam_no')},
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveIntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Course')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Student')),
            ],
            options={
                'unique_together': {('student_email', 'course_id', 'sec_no')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_no', models.PositiveIntegerField()),
                ('comment_no', models.PositiveIntegerField()),
                ('student_email', models.CharField(max_length=20)),
                ('comment_info', models.CharField(max_length=1000)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntnyPth.Course')),
            ],
            options={
                'unique_together': {('course_id', 'post_no', 'comment_no')},
            },
        ),
    ]
