# Generated by Django 3.0.5 on 2020-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntnyPth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_no',
            field=models.IntegerField(),
        ),
    ]
