# Generated by Django 3.0.5 on 2020-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntnyPth', '0002_auto_20200426_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='grade',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
    ]
