# Generated by Django 3.0.5 on 2020-04-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntnyPth', '0003_enroll_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='raw_grade',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
